### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BayuDC** [PraditaAdiantama/spw-api#1]
- [ ] Product database seeder
- [ ] Endpoint: GET /products
- [ ] Endpoint: GET /products/:id
- [ ] Endpoint: POST /products
- [ ] Endpoint: PUT /products/:id
- [ ] Endpoint: DELETE /products/:id
